export const USER_SIGNIN_REQUESTED = 'USER_SIGNIN_REQUESTED'
export const USER_SIGNIN_SUCCEEDED = 'USER_SIGNIN_SUCCEEDED'
export const USER_SIGNIN_FAILED = 'USER_SIGNIN_FAILED'

export const USER_SIGNOUT_REQUESTED = 'USER_SIGNOUT_REQUESTED'
export const USER_SIGNOUT_SUCCEDDED = 'USER_SIGNOUT_SUCCEDDED'
export const USER_SIGNOUT_FAILED = 'USER_SIGNOUT_FAILED'

export const FETCH_COMPETITIONS_REQUESTED = 'FETCH_COMPETITIONS_REQUESTED'
export const FETCH_COMPETITIONS_SUCCEEDED = 'FETCH_COMPETITIONS_SUCCEEDED'
export const FETCH_COMPETITIONS_FAILED = 'FETCH_COMPETITIONS_FAILED'

export const CREATE_COMPETITION_REQUESTED = 'CREATE_COMPETITION_REQUESTED'
export const CREATE_COMPETITION_SUCCEEDED = 'CREATE_COMPETITION_SUCCEEDED'
export const CREATE_COMPETITION_FAILED = 'CREATE_COMPETITION_FAILED'

export const CHANGE_COMPETITION_NAME_REQUESTED = 'CHANGE_COMPETITION_NAME_REQUESTED'
export const CHANGE_COMPETITION_NAME_SUCCEEDED = 'CHANGE_COMPETITION_NAME_SUCCEEDED'
export const CHANGE_COMPETITION_NAME_FAILED = 'CHANGE_COMPETITION_NAME_FAILED'

export const ERASE_COMPETITION_REQUESTED = 'ERASE_COMPETITION_REQUESTED'
export const ERASE_COMPETITION_SUCCEEDED = 'ERASE_COMPETITION_SUCCEEDED'
export const ERASE_COMPETITION_FAILED = 'ERASE_COMPETITION_FAILED'

export const ADD_COMPETITION_PARTICIPANT_REQUESTED = 'ADD_COMPETITION_PARTICIPANT_REQUESTED'
export const ADD_COMPETITION_PARTICIPANT_SUCCEDDED = 'ADD_COMPETITION_PARTICIPANT_SUCCEDDED'
export const ADD_COMPETITION_PARTICIPANT_FAILED = 'ADD_COMPETITION_PARTICIPANT_FAILED'

export const REMOVE_COMPETITION_PARTICIPANT_REQUESTED = 'REMOVE_COMPETITION_PARTICIPANT_REQUESTED'
export const REMOVE_COMPETITION_PARTICIPANT_SUCCEDDED = 'REMOVE_COMPETITION_PARTICIPANT_SUCCEDDED'
export const REMOVE_COMPETITION_PARTICIPANT_FAILED = 'REMOVE_COMPETITION_PARTICIPANT_FAILED'

export const SEND_MAIL_REQUESTED = 'SEND_MAIL_REQUESTED'
export const SEND_MAIL_SUCCEDDED = 'SEND_MAIL_SUCCEDDED'
export const SEND_MAIL_FAILED = 'SEND_MAIL_FAILED'

export const COMPETITIONS_UPDATED = 'COMPETITIONS_UPDATED'